name: JS and TS tests
on:
  push:
jobs:
  tests:
    strategy:
      matrix:
        node-version: [ '14.x', '16.x', '18.x' ,'20.x' ,'latest']
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests on ${{ matrix.node-version }}
        run: node tests/tests-node.js

      - name: Setup Bun
        uses: https://github.com/oven-sh/setup-bun@v2
        with:
          bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip"

      - name: Run tests on Bun
        run: bun tests/tests-bun.ts 
