name: Bun TS tests
on:
  push:
jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Bun
        uses: https://github.com/oven-sh/setup-bun@v2
        with:
          bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip"

      - name: Run tests
        run: bun tests/tests-bun.ts 
