name: JS and TS tests
on:
  push:
  pull_request:
jobs:
  tests:
    strategy:
      matrix:
        node-version: [ '14.x', '16.x', '18.x' ,'20.x' ,'latest' ]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests on ${{ matrix.node-version }}
        run: node tests/tests-node.js

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Run tests on Bun
        run: bun tests/tests-bun.ts 
